import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import NavBar from "@/layout/NavBar";
import axios from "axios";
import Slider1 from "@/components/Slider1";
import MainCategories from "@/components/mainCategories";
import Featured from "@/components/Featured";
const inter = Inter({ subsets: ["latin"] });

export default function Home({ data, category, brandsItems, fearuredItems }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Slider1 data={data[0].image} />
      <h2 className={styles.title}>Main Categories</h2>
      <div className={styles.ItemsCon}>
        {category.map(({ image, name }) => {
          return <MainCategories image={image} title={name} />;
        })}
      </div>
      <img src="../assets/sales.png" className={styles.sale} />
      <img
        src="../assets/image1mobile.png"
        style={{ width: "100%", objectFit: "contain" }}
        className={styles.salemob}
      />

      <div className={styles.ItemsCon}>
        {brandsItems.map(({ image }) => {
          return (
            <MainCategories image={image} title="Up to 40%" brands={true} />
          );
        })}
      </div>
      <img src="../assets/blackNovember.png" style={{ width: "100%" }} />
      <h1 className={styles.title}>Featured Items</h1>
      <div className={styles.ItemsCon}>
        {fearuredItems.map(({ image, price_after_sale, price_before_sale }) => {
          return (
            <Featured
              image={image}
              priceAfter={price_after_sale}
              priceBefore={price_before_sale}
            />
          );
        })}
      </div>
      <h1 className={styles.title}>Most Viewed</h1>

      <div className={styles.ItemsCon}>
        {fearuredItems.map(({ image, price_after_sale, price_before_sale }) => {
          return (
            <Featured
              image={image}
              priceAfter={price_after_sale}
              priceBefore={price_before_sale}
            />
          );
        })}
      </div>
      <div className={styles.sales}>
        <img src="../assets/image1.png" alt="" />
        <img src="../assets/image2.png" alt="" />
      </div>
    
    </>
  );
}
export async function getStaticProps(context) {
  try {
    const result = await axios.get(
      "https://api-task.bit68.com/en/api/slider_image/"
    );
    const categories = await axios.get(
      "https://api-task.bit68.com/en/api/categories/"
    );
    const brands = await axios.get("https://api-task.bit68.com/en/api/brands/");
    const featured = await axios.get(
      "https://api-task.bit68.com/en/api/items/"
    );
    const category = categories.data.results;
    const data = result.data.results;
    const brandsItems = brands.data.results;
    const fearuredItems = featured.data.results;
    return {
      props: {
        data: data,
        category,
        fearuredItems,
        brandsItems,
      },
    };
  } catch (error) {
    console.log(error);
  }
}
